$primary = rgb(7e9cd8)
$surface = rgb(1f1f28)
$secondary = rgb(76946a)
$error = rgb(c34043)
$tertiary = rgb(c0a36e)
$surface_lowest = rgb(21212b)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
