#! /bin/sh

### Configuration ###
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width	1
bspc config window_gap		5
bspc config split_ratio   0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config single_monocle      true

bspc config normal_border_color   \#1a1b26
bspc config active_border_color   \#f7768e
bspc config focused_border_color  \#bb9af7
bspc config presel_feedback_color \#7dcfff

### Rules General
bspc rule -a \* follow=on
### Rules Desktops ###
bspc rule -a firefox          desktop=2
bspc rule -a Chromium         desktop=2

bspc rule -a TelegramDesktop  desktop=3
bspc rule -a discord          desktop=3

bspc rule -a Code             desktop=4

bspc rule -a Gimp-2.10        desktop=5

bspc rule -a Xreader          desktop=6
bspc rule -a libreoffice      desktop=6

bspc rule -a feh              desktop=8
bspc rule -a Sxiv             desktop=8
bspc rule -a vlc              desktop=8
bspc rule -a mpv              desktop=8

bspc rule -a obs              desktop=9

### Rules Floatings ###
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Gcolor3 state=floating

### Setting default monocle desktops
bspc desktop 1 -l monocle
bspc desktop 2 -l monocle
bspc desktop 8 -l monocle
