#!/bin/sh

# Apps
#
# Terminal
super + Return
  alacritty
# Open and attach tmux
super + {alt,shift} + Return
  alacritty -e {tmux,tmux a}
# ranger
super + {f,v}
  bspc rule -a Alacritty -o state=floating & alacritty -e {ranger, nvim}
# Fast open ScreenShots
super + shift + f
  bspc rule -a Alacritty -o desktop=8 & alacritty -e ranger ~/Pictures/ScreenShots/
# htop
super + shift + Escape
  alacritty -e htop
# firefox
super + b
  firefox
# telegram
super + t
  telegram-desktop


# Utilities
#
# Rofi program launcher
super + {control, alt} + @space
  rofi -show {_, drun}
# ScreenShots savefile
super + {_, control +} Print
  maim {_, -s -u} ~/Pictures/ScreenShots/$(date +%F-%T).png
# ScreenShots clipboard
alt + {_, control +} Print
  maim {_, -s -u} | xclip -selection clipboard -t image/png -i


# bspwm hotkeys
#
# login off / restart bspwm
super + control + {q, r}
  bspc {quit, wm -r}
# block screen
super + control + s
  betterlockscreen -l dim
# close and kill
super + {shift,control} + w
  bspc node -{c,k}
# make sxhkd reload its configuration files:
super + Escape
  pkill -USR1 -x sxhkd


# state
#
# set the window state
super + shift + {u,i,o}
  bspc node -t {fullscreen,tiled,floating}
# alternate between the tiled and monocle layout
super + shift + m 
  bspc desktop -l next
# swap the current node and the biggest window in current desktop
super + shift + g
  bspc node -s biggest.window.local
# focus the next/previous occupied desktop
super + {_,shift + } Tab
  bspc desktop {next,prev}.occupied -f


# focus/swap
#
# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
  bspc node -{f,s} {west,south,north,east}
# focus the next/previous window in the current desktop
super + {_,shift + }@space
  bspc node -f {next,prev}.local.!hidden.window
# focus or send to the given desktop
super + {_,shift + }{1-9,0}
  bspc {desktop -f,node -d} '^{1-9,10}'
# focus the node for the given path jump
super + shift + p
  bspc node -f @parent


# preselect
#
# preselect the direction
super + ctrl + {h,j,k,l}
  bspc node -p {west,south,north,east}
# preselect the ratio
super + ctrl + {1-9}
  bspc node -o 0.{1-9}
# cancel the preselection for the focused node
super + ctrl + p
  bspc node -p cancel
# cancel the preselection for the focused desktop
super + ctrl + shift + p
  bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel


# move/resize
#
# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
  bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}
# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
  bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}
# move a floating window
super + {Left,Down,Up,Right}
  bspc node -v {-10 0,0 10,0 -10,10 0}
