# See https://wiki.hypr.land/Configuring/Variables/

source = ~/.config/hypr/theme.conf

# Colors
$color_accent = $color04
$color_accent_alt = $color06
$color_inactive = $bg1

$font = Noto
$font_mono = JetBrains Mono
# Windows
$border            = 2
$rounding          = 4
$gaps_in           = 4
$gaps_out          = 8
$active_opacity    = 1.0
$inactive_opacity  = 1.0
# Groupbar
$groupbar_height   = 8
$groupbar_rounding = 4
$groupbar_gaps_in  = 4
$groupbar_gaps_out = 4
