source = ~/.config/hypr/config.conf

background {
  monitor =
  path = ~/Pictures/Wallpapers/current
  blur_passes = 2
  brightness = 0.5
}

animations {
  bezier = linear,        0.00,  0.00,  1.00,  1.00
  bezier = easeIn,        0.50,  0.00,  0.75,  0.00 # easeInQuart
  bezier = easeOut,       0.25,  1.00,  0.50,  1.00 # easeOutQuart
	bezier = easeInOut,     0.76,  0.00,  0.24,  1.00 # easeInOutQuart

  animation = fadeIn,           1, 5, easeIn
  animation = fadeOut,          1, 5, easeOut
  animation = inputField,       1, 1, linear
  animation = inputFieldDots,   1, 3, easeOut
  animation = inputFieldColors, 1, 3, easeInOut
  animation = inputFieldWidth,  1, 1, linear
}

input-field {
  monitor =
  position = 0, 0
  halign = center
  valign = center

  size = 250, 50
  rounding = $rounding
  outline_thickness = 2
  outer_color =
  inner_color = $bg0

  check_color = $color02
  fail_color = $color01
  dots_size = 0.2
  dots_spacing = 0.2
  font_color = $fg1
  font_family = $font
  placeholder_text = Password
  fade_on_empty = false
}


## Player

#: artwork
image {
  path = ~/.config/hypr/assets/transparent.png
  size = 120
  rounding = $rounding
  border_size = 0
  reload_time = 2
  # reload_cmd = playerctl metadata mpris:artUrl | sed 's/file:\/\///' && cp $(playerctl metadata mpris:artUrl | sed 's/file:\/\///') /tmp/hyprlock_art.png
  reload_cmd = playerctl status > /dev/null 2>&1 && cp $(playerctl metadata mpris:artUrl | sed 's/file:\/\///') /tmp/hyprlock_art.png && echo "/tmp/hyprlock_art.png" || echo "~/.config/hypr/assets/transparent.png"
  position = 0, 145
  halign = center
  valign = bottom
}

#: title
label {
  text = cmd[update:2000] echo "$(playerctl metadata title)"
  color = $fg1
  font_size = 14
  font_family = $font
  position = 0, 100
  halign = center
  valign = bottom
}

#: artist
label {
  text = cmd[update:2000] echo "$(playerctl metadata artist)"
  color = $fg1
  font_size = 12
  font_family = $font
  position = 0, 75
  halign = center
  valign = bottom
}

#: button prev
label {
    text = cmd[update:2000] playerctl status > /dev/null 2>&1 && echo "󰒮" || echo ""
    onclick = playerctl previous
    color = $fg1
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = -50, 30
    halign = center
    valign = bottom
}

#: button next
label {
    text = cmd[update:2000] playerctl status > /dev/null 2>&1 && echo "󰒭" || echo ""
    onclick = playerctl next
    color = $fg1
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 50, 30
    halign = center
    valign = bottom
}

#: button play/pause
label {
    text = cmd[update:2000] playerctl status > /dev/null 2>&1 && (playerctl status | grep -q "Playing" && echo "󰏤" || echo "󰐊") || echo ""
    onclick = playerctl play-pause
    color = $fg1
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 30
    halign = center
    valign = bottom
}
