## name: Kanagawa
## author: Tommaso Laurenzi
## license: MIT
## upstream: https://github.com/rebelot/kanagawa.nvim/

# fg shades
$fg0 = rgb(DCD7BA)
$fg1 = rgb(C8C093)
$fg2 = rgb(727169)
# bg shades
$bg0 = rgb(1F1F28)
$bg1 = rgb(2A2A37)
$bg2 = rgb(363646)
$bg3 = rgb(54546D)
# black
$color00 = rgb(16161d)
$color08 = rgb(727169)
# red
$color01 = rgb(C34043)
$color09 = rgb(E82424)
# green
$color02 = rgb(76946A)
$color10 = rgb(98BB6C)
# yellow
$color03 = rgb(C0A36E)
$color11 = rgb(E6C384)
# blue
$color04 = rgb(7E9CD8)
$color12 = rgb(7FB4CA)
# magenta
$color05 = rgb(957FB8)
$color13 = rgb(938AA9)
# cyan
$color06 = rgb(6A9589)
$color14 = rgb(7AA89F)
# white
$color07 = rgb(C8C093)
$color15 = rgb(DCD7BA)
# extended
$color16 = rgb(ffa066)
$color17 = rgb(ff5d62)
