# Load .profile if exists
if [ -f "${HOME}/.profile" ];then
  source "${HOME}/.profile"
fi

# Zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# Plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

# Options
autoload -U compinit && compinit -d "${XDG_CACHE_HOME}/zsh/zcompdump"
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

# History
HISTSIZE=5000
HISTFILE="${XDG_STATE_HOME}/zsh/history"
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_find_no_dups

# Keymaps
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# Alias
alias ls='ls -Fvh --color=auto --group-directories-first'
alias la='ls -A'
alias lls='ls -l'
alias lla='ls -lA'
alias tree='tree -C'
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias rm="rm -i"
alias du="du -h"
alias wget='wget --hsts-file="$XDG_DATA_HOME/wget-hsts"'
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

# Autocmd
eval "$(fzf --zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init --cmd=cd zsh)"
fastfetch
# PF_INFO="ascii title os host wm uptime memory disk" pfetch
