;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = "./modules.ini"

[colors]
bg      = #1a1b26
fg      = #c0caf5
ng      = #00000000

black   = #414868
red     = #f7768e
green   = #9ece6a
yellow  = #e0af68
blue    = #7aa2f7
magenta = #bb9af7
cyan    = #7dcfff
white   = #c0caf5
gray    = #40486a

[bar/example]
width = 1356px
height = 19
radius = 0

offset-x = 5px
offset-y = 5px
; dpi = 96

background = ${colors.bg}
foreground = ${colors.fg}

line-size = 3

border-bottom-size = 3
border-top-size = 3
border-color = ${colors.bg}

padding-left = 3px
padding-right = 3px

module-margin = 0

font-0 = Ubuntu Nerd Font:pixelsize=10;2
font-1 = JetBrains Mono Nerd Font:pixelsize=13;4
font-2 = JetBrains Mono Nerd Font:pixelsize=12;3
font-3 = Togalite bold:pixelsize=10;2

modules-left = archico spl-red spl-bg-blue bspwm spl-blue 
modules-center = spr-magenta xwindow spl-magenta 
modules-right = spr-cyan pulseaudio spr-bg-cyan spr-green memory spr-bg-green spr-yellow cpu spr-bg-yellow spr-white date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-detached = true
tray-position = left
tray-offset-x = 290

wm-restack = bspwm

[settings]
screenchange-reload = true
pseudo-transparency = true
