[module/spl-black]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.black}
[module/spr-black]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.black}

[module/spl-red]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.red}
[module/spr-red]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.red}

[module/spl-green]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.green}
[module/spr-green]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.green}

[module/spl-yellow]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.yellow}
[module/spr-yellow]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.yellow}

[module/spl-blue]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.blue}
[module/spr-blue]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.blue}

[module/spl-magenta]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.magenta}
[module/spr-magenta]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.magenta}

[module/spl-cyan]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.cyan}
[module/spr-cyan]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.cyan}

[module/spl-white]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.white}
[module/spr-white]
type = custom/text
content = ""
content-font = 3
content-foreground = ${colors.white}

; Separators bg-color
[module/spl-bg-black]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.black}
[module/spr-bg-black]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.black}
[module/spl-bg-red]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.red}
[module/spr-bg-red]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.red}
[module/spl-bg-green]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.green}
[module/spr-bg-green]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.green}
[module/spl-bg-yellow]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.yellow}
[module/spr-bg-yellow]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.yellow}
[module/spl-bg-blue]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.blue}
[module/spr-bg-blue]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.blue}
[module/spl-bg-magenta]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.magenta}
[module/spr-bg-magenta]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.magenta}
[module/spl-bg-cyan]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.cyan}
[module/spr-bg-cyan]
type = custom/text
content = ""
content-font=3
jkkontent-foreground = ${colors.bg}
content-background = ${colors.cyan}
[module/spl-bg-white]
type = custom/text
content = ""
content-font=3
content-foreground = ${colors.bg}
content-background = ${colors.white}
[module/spr-bg-white]
type = custom/text
content = ""
content-font=3
jkkontent-foreground = ${colors.bg}
content-background = ${colors.white}
