### General ###
set -sa terminal-overrides ',alacritty:RGB'
set -g escape-time 0
set -g prefix C-a
unbind C-b
## Screen saver
set -g lock-after-time 300
set -g lock-command 'cmatrix -s -C red -M "Game Over"'

set -g base-index 1
setw -g pane-base-index 1

setw -g automatic-rename off

### Blindings ###
## Copy/Paste and copy mode
setw -g mode-keys vi
unbind [
bind v copy-mode
unbind p
bind p paste-buffer
bind C-y run 'tmux save-buffer - | xclip -i -sel clipboard'
bind C-p run 'tmux set-buffer "$(xclip -o -sel clipboard)"; tmux paste-buffer'
## Others
bind r source-file ~/.config/tmux/tmux.conf \; display 'tmux.conf sourced'
bind M-b set-option status
## Vim movement
bind h select-pane -L 
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# resize panes
bind -r M-h resize-pane -L
bind -r M-j resize-pane -D
bind -r M-k resize-pane -U
bind -r M-l resize-pane -R
bind -r M-H resize-pane -L 5
bind -r M-J resize-pane -D 5
bind -r M-K resize-pane -U 5
bind -r M-L resize-pane -R 5
# to cycle through windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind C-b last-window


## Status bar
# icons  
set -g status-interval 1
set -g status-keys vi
set -g status-position bottom
set -g status-justify left
set -g status-style bg='#1d1e29'

set -g status-left-length 100
set -g status-left '#[fg=#1d1e29,bg=red] #S #[fg=red,bg=#1d1e29]#[fg=#1d1e29,bg=blue]#[fg=#1d1e29,bg=blue] #P #[fg=blue,bg=#1d1e29]'
set -g status-right-length 100
set -g status-right '#[fg=black,bg=#1d1e29]#[fg=white,bg=black] %D  %T #[fg=#1d1e29,bg=black]#[fg=white,bg=#1d1e29]#[fg=#1d1e29,bg=white] #H #[fg=#1d1e29,bg=white]#[fg=yellow,bg=#1d1e29]#[fg=black,bg=yellow] #{user} '

setw -g window-status-separator ''
setw -g window-status-format '#[fg=#545c7e] #I  #W '
setw -g window-status-current-format '#[bg=magenta,fg=#1d1e29]#[fg=black,bg=magenta,bold] #I  #W  #F #[fg=magenta,bg=#1d1e29]'

### Plugins ###
## List
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
## Config
set -g @resurrect-processes '"ranger->ranger $HOME" cava cmatrix tty-clock'
set -g @resurrect-dir '~/.config/tmux/resurrect/'
## Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm
