[flavor]
dark = "kanagawa"

[tabs]
active   = { fg = "#1f1f28", bg = "#7e9cd8", bold = true }
inactive = { fg = "#7e9cd8", bg = "#2a2a37" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }
